name: Deploy Chat Bot to AWS EBS with base image
on:
  push:
    branches:
      - "backend"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Web-ChatBot
          environment_name: Develop-Web-ChatBot-env
          version_label: ${{ github.sha }}
          region: us-east-2
          use_existing_version_if_available: true
          deployment_package: deploy.zip